#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../../autoload.php')) {
	require __DIR__ . '/../../../autoload.php';
} elseif (file_exists(__DIR__ . '/../vendor/autoload.php')) {
	require __DIR__ . '/../vendor/autoload.php';
} else {
	throw new \RuntimeException(
		'Could not find composer autoloader file. Did you run "composer install?"'
	);
}

use Symfony\Component\Console\Application;
use Ublaboo\Anabelle\Console\GenerateDocuCommand;

$application = new Application('anabelle');

$application->add($command = new GenerateDocuCommand(__DIR__));

$application->setDefaultCommand($command->getName(), true);
$application->run();

exit(0);
