#!/usr/bin/env php
<?php

require __DIR__ . '/../../../autoload.php';

use Symfony\Component\Console\Application;
use Ublaboo\Anabelle\Console\GenerateDocuCommand;

$application = new Application('anabelle');

$application->add($command = new GenerateDocuCommand(__DIR__));

$application->setDefaultCommand($command->getName(), true);
$application->run();

exit(0);
