name: "Nette Tester"

on:
    pull_request:

    push:
        branches: [ "*" ]

    schedule:
        -   cron: "0 8 * * 1"

jobs:
    php82:
        name: "Nette Tester"
        uses: contributte/.github/.github/workflows/nette-tester.yml@master
        with:
            php: "8.2"

    php81:
        name: "Nette Tester"
        uses: contributte/.github/.github/workflows/nette-tester.yml@master
        with:
            php: "8.1"

    phplower:
        name: "Nette Tester"
        uses: contributte/.github/.github/workflows/nette-tester.yml@master
        with:
            php: "8.1"
            composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
